[package]
name = "altbinutils"
version = "2021.2.1-alpha.1"
authors = ["Eray Erdin <eraygezer.94@gmail.com>"]
edition = "2018"
description = "Alternative Binary Utilities"

[dependencies]
directories = "3.0.1"
log = "0.4.14"

[dev-dependencies]
rstest = "0.9.0"
simple_logger = "1.11.0"
