[package]
name = "app_lse"
version = "0.1.0"
edition = "2018"

[dependencies]
async-std = "1.10.0"
async-trait = "0.1.51"

[dependencies.altbinutils]
path = ".."

[[bin]]
name = "lse"
path = "src/main.rs"
