[package]
name = "rment"
version = "2021.2.1-alpha.1"
edition = "2018"
description = "Removes files and directories."

[dependencies]
altbinutils = { path = "../.." }

[dev-dependencies]
rstest = "0.10.0"
assert_cmd = "1.0.7"